[package]
name = "lotus_engine"
version = "0.1.1"
authors = ["Alexandre Zeni <zenialexandre123@gmail.com>"]
description = "Lotus is a game engine with the main focus of being easy-to-use and straight forward on developing 2D games."
license = "MPL-2.0"
edition = "2021"

[dependencies]
winit = { version = "0.30", features = ["rwh_05"] }
env_logger = "0.11.7"
log = "0.4.27"
wgpu = "24.0.3"
pollster = "0.4"
bytemuck = { version = "1.22.0", features = [ "derive" ] }
image = { version = "0.25.6", features = ["png", "jpeg"] }
anyhow = "1.0.97"
cgmath = "0.18"
uuid = { version = "1.16.0", features = ["v4"] }
lotus_proc_macros = { path = "lotus_proc_macros", version = "0.1.1" }
rand = "0.9.0"
strum = "0.27.1"
strum_macros = "0.27.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-leve = 3
